[package]
name = "radarpub"
description = "Raivin Radar Publisher"
repository = "https://bitbucket.org/au-zone/radarpub"
license = "CLOSED"
version = "0.0.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true

[dependencies]
drvegrd = { git = "ssh://git@bitbucket.org/au-zone/drvegrd-rs.git" }
deepviewrt = { git = "https://github.com/DeepViewML/deepviewrt-rs", branch = "RVN-130" }
async-std = {version = "1.12", features = ["attributes"] }
cdr = "0.2"
clap = { version = "4.4", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
serde = "1.0"
serde_derive = "1.0"
socketcan = { version = "3.3", features = ["async-std"] }
unix-ts = "0.6.0"
zenoh = "0.10.0-rc"
zenoh-ros-type = { git = "https://github.com/MaivinAI/zenoh-ros-type" }
futures = "0.3"