[package]
name = "radarpub"
description = "Raivin Radar Publisher"
repository = "https://bitbucket.org/au-zone/radarpub"
license = "CLOSED"
version = "0.0.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
debug = true

[dependencies]
drvegrd = { git = "ssh://git@bitbucket.org/au-zone/drvegrd-rs.git", rev = "5e9486c" }
async-std = {version = "1.12", features = ["attributes"] }
cdr = "0.2"
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
serde = "1.0"
serde_derive = "1.0"
socketcan = { version = "3.3", features = ["async-std"] }
unix-ts = "0.6.0"
zenoh = "0.10.0-rc"
zenoh-ros-type = { git = "https://github.com/MaivinAI/zenoh-ros-type", branch = "main" }
futures = "0.3"
ndarray = "0.15"
ndarray-npy = "0.8"
rerun = "0.14.1"
kanal = "0.1.0-pre8"
