[package]
name = "radarpub"
description = "Raivin Radar Publisher"
repository = "https://bitbucket.org/au-zone/radarpub"
license = "CLOSED"
version = "0.0.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
strip = true
debug = false

[profile.profiling]
inherits = "release"
strip = false
debug = true

[dependencies]
drvegrd = { git = "ssh://git@bitbucket.org/au-zone/drvegrd-rs.git", tag = "1.3.4", features = [ "can" ] }
edgefirst-schemas = "1.2.4"
async-std = { version = "1.12", features = ["attributes"] }
cdr = "0.2"
clap = { version = "4.5", features = ["derive", "env"] }
log = "0.4.22"
env_logger = "0.11.5"
serde = "1.0"
serde_derive = "1.0"
socketcan = { version = "3.3", features = ["async-std"] }
unix-ts = "1.0"
zenoh = "0.10.0-rc"
futures = "0.3"
ndarray = "0.16.1"
kanal = { git = "https://github.com/fereidani/kanal", rev = "125fb78" }
libc = "0.2"
rerun = { version = "0.18.2", optional = true }
dbscan = "0.3.1"
lapjv = "0.2.1"
uuid = { version = "1.11.0", features = ["v4"] }
nalgebra = "0.33.2"

[features]
rerun = ["dep:rerun"]
